const deklination = [
    {
        type: "Keiner Artikel",
        data: [
            { casus: "nominativ", person: "maskulin", ending: "er" },
            { casus: "akkusativ", person: "maskulin", ending: "en" },
            { casus: "dativ", person: "maskulin", ending: "em" },
            { casus: "genitiv", person: "maskulin", ending: "en" },
            { casus: "nominativ", person: "feminin", ending: "e" },
            { casus: "akkusativ", person: "feminin", ending: "e" },
            { casus: "dativ", person: "feminin", ending: "er" },
            { casus: "genitiv", person: "feminin", ending: "er" },
            { casus: "nominativ", person: "neutral", ending: "es" },
            { casus: "akkusativ", person: "neutral", ending: "es" },
            { casus: "dativ", person: "neutral", ending: "em" },
            { casus: "genitiv", person: "neutral", ending: "en" },
            { casus: "nominativ", person: "plural", ending: "e" },
            { casus: "akkusativ", person: "plural", ending: "e" },
            { casus: "dativ", person: "plural", ending: "en" },
            { casus: "genitiv", person: "plural", ending: "er" },
        ],
    },
    {
        type: "Bestimmter Artikel",
        data: [
            { casus: "nominativ", person: "maskulin", ending: "e" },
            { casus: "akkusativ", person: "maskulin", ending: "en" },
            { casus: "dativ", person: "maskulin", ending: "en" },
            { casus: "genitiv", person: "maskulin", ending: "en" },
            { casus: "nominativ", person: "feminin", ending: "e" },
            { casus: "akkusativ", person: "feminin", ending: "e" },
            { casus: "dativ", person: "feminin", ending: "en" },
            { casus: "genitiv", person: "feminin", ending: "en" },
            { casus: "nominativ", person: "neutral", ending: "e" },
            { casus: "akkusativ", person: "neutral", ending: "e" },
            { casus: "dativ", person: "neutral", ending: "en" },
            { casus: "genitiv", person: "neutral", ending: "en" },
            { casus: "nominativ", person: "plural", ending: "en" },
            { casus: "akkusativ", person: "plural", ending: "en" },
            { casus: "dativ", person: "plural", ending: "en" },
            { casus: "genitiv", person: "plural", ending: "en" },
        ],
    },
    {
        type: "Unbestimmter Artikel",
        data: [
            { casus: "nominativ", person: "maskulin", ending: "er" },
            { casus: "akkusativ", person: "maskulin", ending: "en" },
            { casus: "dativ", person: "maskulin", ending: "en" },
            { casus: "genitiv", person: "maskulin", ending: "en" },
            { casus: "nominativ", person: "feminin", ending: "e" },
            { casus: "akkusativ", person: "feminin", ending: "e" },
            { casus: "dativ", person: "feminin", ending: "en" },
            { casus: "genitiv", person: "feminin", ending: "en" },
            { casus: "nominativ", person: "neutral", ending: "es" },
            { casus: "akkusativ", person: "neutral", ending: "es" },
            { casus: "dativ", person: "neutral", ending: "en" },
            { casus: "genitiv", person: "neutral", ending: "en" },
            { casus: "nominativ", person: "plural", ending: "e" },
            { casus: "akkusativ", person: "plural", ending: "e" },
            { casus: "dativ", person: "plural", ending: "en" },
            { casus: "genitiv", person: "plural", ending: "er" },
        ],
    },
]
